export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const REMOVE_ALL_TODOS = 'REMOVE_ALL_TODO';

export const LOGIN_DATA = 'LOGIN_DATA';
export const LOGIN_DATA_SUCESS = 'SIGNUP_DATA_SUCESS';
export const LOGIN_FAIL = 'SIGNUP_FAIL';

export const SIGNUP_DATA = 'SIGNUP_DATA';
export const SIGNUP_DATA_SUCESS = 'SIGNUP_DATA_SUCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';


export const CREATE_AUCTION = 'CREATE_AUCTION';
export const CREATE_AUCTION_SUCESS = 'CREATE_AUCTION_SUCESS';
export const CREATE_AUCTION_FAIL = 'CREATE_AUCTION_FAIL';




